/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Ctrl_Cliente;
import controlador.Ctrl_Tarifa;
import controlador.Ctrl_Vehiculo;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Vehiculo;

/**
 *
 * @author Usuario
 */
public class panelIngresarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form panelUsuarios
     */
    public panelIngresarVehiculo() {
        initComponents();
        this.setSize(960, 600);
    }
    private Ctrl_Tarifa ctrlTarifa = new Ctrl_Tarifa();
    private Ctrl_Cliente ctrlCliente = new Ctrl_Cliente();
    private Ctrl_Vehiculo ctrlVehiculo = new Ctrl_Vehiculo();
    private boolean ingreso = false;
    private Vehiculo vehiculoIngreso;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnIngresarVehiculo = new javax.swing.JButton();
        txtPatente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDniDuen = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        paneLupa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbTipoVehiculo = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Patente:");

        btnIngresarVehiculo.setBackground(new java.awt.Color(0, 102, 153));
        btnIngresarVehiculo.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnIngresarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarVehiculo.setText("Ingresar Vehiculo");
        btnIngresarVehiculo.setBorderPainted(false);
        btnIngresarVehiculo.setFocusPainted(false);
        btnIngresarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarVehiculoActionPerformed(evt);
            }
        });

        txtPatente.setBackground(new java.awt.Color(153, 153, 153));
        txtPatente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtPatente.setForeground(new java.awt.Color(51, 51, 51));
        txtPatente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPatente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPatenteMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" Ingresar Vehiculo");

        txtDniDuen.setBackground(new java.awt.Color(0, 51, 102));
        txtDniDuen.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        txtDniDuen.setForeground(new java.awt.Color(255, 255, 255));
        txtDniDuen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniDuen.setText("Ingrese el dni del dueño aqui.......");
        txtDniDuen.setBorder(null);
        txtDniDuen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDniDuenMouseClicked(evt);
            }
        });
        txtDniDuen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniDuenActionPerformed(evt);
            }
        });
        txtDniDuen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDniDuenKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo de Vehiculo");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre: ");

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(0, 51, 102));
        txtApellido.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellido.setBorder(null);

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(0, 51, 102));
        txtNombre.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(null);

        paneLupa.setBackground(new java.awt.Color(0, 51, 102));
        paneLupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneLupaMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa logo.png"))); // NOI18N

        javax.swing.GroupLayout paneLupaLayout = new javax.swing.GroupLayout(paneLupa);
        paneLupa.setLayout(paneLupaLayout);
        paneLupaLayout.setHorizontalGroup(
            paneLupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLupaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneLupaLayout.setVerticalGroup(
            paneLupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLupaLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Datos del dueño");

        cmbTipoVehiculo.setBackground(new java.awt.Color(153, 153, 153));
        cmbTipoVehiculo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbTipoVehiculo.setForeground(new java.awt.Color(51, 51, 51));
        cmbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo:", "Auto", "Camioneta", "Moto" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addComponent(btnIngresarVehiculo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(paneLupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDniDuen, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 179, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(paneLupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDniDuen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(btnIngresarVehiculo)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void paneLupaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneLupaMouseClicked
        buscarCliente();
    }//GEN-LAST:event_paneLupaMouseClicked

    private void txtDniDuenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniDuenActionPerformed

    }//GEN-LAST:event_txtDniDuenActionPerformed

    private void txtDniDuenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniDuenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarCliente();
        }
    }//GEN-LAST:event_txtDniDuenKeyPressed

    private void txtDniDuenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniDuenMouseClicked
        if (txtPatente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese primero la patente.");
        } else if (txtDniDuen.getText().equals("Ingrese el dni del dueño aqui.......")) {
            txtDniDuen.setText("");
        }
    }//GEN-LAST:event_txtDniDuenMouseClicked

    private void txtPatenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPatenteMouseClicked
        if (txtDniDuen.getText().equals("")) {
            txtDniDuen.setText("Ingrese el dni del dueño aqui.......");
        }
    }//GEN-LAST:event_txtPatenteMouseClicked

    private void btnIngresarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarVehiculoActionPerformed
        buscarCliente();
        if (ingreso == true) {
            if (cmbTipoVehiculo.getSelectedIndex() != 0) {
                if (ctrlVehiculo.vehiculoEnEstablecimiento(txtPatente.getText()) == false) {
                    vehiculoIngreso = crearInstanciaVehiculo();
                    if (ctrlTarifa.generarTarifaIngreso(vehiculoIngreso)) {
                        if (ctrlVehiculo.ingresarVehiculo(vehiculoIngreso)) {
                            mostrarMensajeAviso("Vehiculo Ingresado Exitosamente!");
                        }    
                         else {
                        mostrarMensajeAviso("Error al ingresar vehiculo. Intente nuevamente.");
                        }
                    }else{
                        mostrarMensajeAviso("Error al generar la tarifa de ingreso. Por favor intente nuevamente.");
                    }
                } else {
                    mostrarMensajeAviso("El vehiculo con patente " + txtPatente.getText() + " se encuentra en el establecimiento.");
                }
            } else {
                mostrarMensajeAviso("Por favor, seleccione un tipo de vehiculo.");
            }
        }
    }//GEN-LAST:event_btnIngresarVehiculoActionPerformed

    // este metodo debo invocarlo en jPanel2MouseClicked y en txtDniDuenActionPerformed
    private void buscarCliente() {
        if (!txtPatente.getText().equals("")) {
            if (!txtDniDuen.getText().equals("") && (!txtDniDuen.getText().equals("Ingrese el dni del dueño aqui......."))) {
                Cliente clienteBuscado = ctrlCliente.retornarNombreCompleto(txtDniDuen.getText());
                if (clienteBuscado != null) {
                    txtApellido.setText(clienteBuscado.getApellido());
                    txtNombre.setText(clienteBuscado.getNombre());
                    ingreso = true;
                } else {
                    mostrarMensajeAviso("El dni ingresado: " + txtDniDuen.getText() + " no corresponde a un cliente nuestro.");
                }
            } else {
                mostrarMensajeAviso("Por favor, ingrese un dni");
            }
        } else {
            mostrarMensajeAviso("Por favor, ingrese una patente.");
        }
    }

    private void mostrarMensajeAviso(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    private Vehiculo crearInstanciaVehiculo() {
        String dniDuen = txtDniDuen.getText();
        String patente = txtPatente.getText().toUpperCase(); // lo guardamos en mayuscula.
        String tipoVehiculo = cmbTipoVehiculo.getSelectedItem().toString();
        String ubicacion = "Dentro del establecimiento";
        Vehiculo vehiculo = new Vehiculo(dniDuen, patente, tipoVehiculo, ubicacion);
        return vehiculo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarVehiculo;
    private javax.swing.JComboBox<String> cmbTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel paneLupa;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDniDuen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPatente;
    // End of variables declaration//GEN-END:variables
}
